[package]
name = "collatz-at-home"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.24.0"
pollster = "0.4.0"
wgpu = {version = "0.16", features = ["webgl"]}
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3", features = ["console"] }